chore: specify vault role & mount point for populate and es
jenkins-x/jx3-versions pull request #3270
Opened 2022-08-18 16:14 UTC by JordanGoasdoue

2022-08-18 17:07 UTC, cyrinux approved these changes

2022-08-19 09:30 UTC, tomhobson requested changes

2022-08-19 09:30 UTC, tomhobson commented on src/Makefile.mk
> +VAULT_MOUNT_POINT_EXTERNAL_SECRETS ?= ${VAULT_MOUNT_POINT}
Can we add some comments as to how and why these exist and are used?

2022-08-19 13:37 UTC, tomhobson approved these changes

2022-08-24 14:53 UTC, ankitm123 commented
@JordanGoasdoue release pipeline is somewhat fixed, can u rebase ur jx3 version with the latest master?

2022-08-24 15:16 UTC, ankitm123 commented
/test gsm

2022-08-24 15:30 UTC, ankitm123 commented
/test gsm

2022-08-24 15:31 UTC, ankitm123 commented
Previous job died because of spot instance shutting down.

2022-08-24 16:18 UTC, ankitm123 commented
/test gsm

2022-08-24 17:06 UTC, ankitm123 commented
Passed:
```
Ran 1 of 1 Specs in 989.927 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSuite (989.93s)
PASS
ok  	github.com/jenkins-x/bdd-jx/test/suite/spring	989.949s
pod jx-bdd-gh2x8 has Succeeded
job jx-bdd has Succeeded
POD RESULT: OK
```

2022-08-24 17:06 UTC, ankitm123 commented
/override gsm

2022-08-24 17:07 UTC, merged